# Generated by Django 4.2.3 on 2023-07-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletList', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clearance', models.CharField(choices=[('T', 'Teacher'), ('C', 'Caseworker')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('learning_plan', models.CharField(choices=[('IEP', 'Individualized Educational Plan'), ('504', '504 Plan')], max_length=3)),
                ('teacher_suggestions', models.TextField()),
                ('accomodations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='hub.accomodation')),
                ('teachers', models.ManyToManyField(to='hub.user')),
            ],
        ),
    ]
