# Generated by Django 4.2.3 on 2023-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='bulletList',
            new_name='bullet_list',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='student_name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
