# Generated by Django 4.2.3 on 2023-07-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_rename_bulletlist_accomodation_bullet_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='caseworker',
            field=models.ForeignKey(default='caseworker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='caseworker', to='hub.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='accomodations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accomodations', to='hub.accomodation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', to='hub.user'),
        ),
    ]
